### ISSUE TITLE
typeDefault has no Effect

### ISSUE THREAD

**Issue by eugenkiss** [GitbookIO/slate-edit-list#25]
It seems that setting the value for `typeDefault` has no effect. It keeps being `paragraph` even if you provide another value. Searching for `typeDefault` in this project (https://github.com/GitbookIO/slate-edit-list/search?utf8=%E2%9C%93&q=typeDefault) suggests that the value is set but never used.

**Comment by Soreine** [comment]
Indeed, it's not actually used. We'll remove it for now.

**Comment by Soreine** [comment]
My bad, it is used [here](https://github.com/GitbookIO/slate-edit-list/blob/d288923b53b9d609907ae10b956b1906017b58cf/lib/makeSchema.js#L133)

The default type is only used when an item does not contain any block, and must be normalized by the schema. The rest of the plugin works with whatever block is already present. When would you expect the plugin to use `typeDefault` otherwise ?

**Comment by eugenkiss** [comment]
Oh, now that I think about it I had a wrong assumption about the behavior of `typeDefault`. I thought it will be used as a wrapper around the item in any case. For example, if `typeDefault` is `paragraph2`, a `paragraph` that is wrapped inside a list item will be wrapped additionally inside a `paragraph2`. Sorry for the confusion.

**Comment by klis87** [comment]
I also thought this would be used as itemList direct descendand, woudnt it be nice actually? For example I need too apply trailing commas, dots or colons depending on the depth and position of a list item, so I need to override the paragraph renderer. I think it would be cleaner to allow custom itemList descendant by `typeDefault` property
