### ISSUE TITLE
Weird cursor move after backspace at start of second list

### ISSUE THREAD

**Issue by ianstormtaylor** [GitbookIO/slate-edit-list#35]
I'm seeing a weird behavior when backspacing at the start of a second list:

![](http://g.recordit.co/941ZJqeNRt.gif)

And here it is in my editor (where there isn't a paragraph between them):

![](http://g.recordit.co/AGvnj7d5uT.gif)

**Comment by wells** [comment]
This behavior also occurs in general if you remove the first list item from a list with Backspace. The list item is transformed to a paragraph and the cursor moves to the end of the previous block.

![example gif](http://i.giphy.com/d3mo6J1r00uK1VkI.gif)

**Comment by oyeanuj** [comment]
Here is another example, which seems related. On the nested list, after entering one list item, pressed enter, then backspace and then enter again. Instead of exiting the list, the first list item is transformed to a paragraph.

![slate list broken](https://cloud.githubusercontent.com/assets/9633371/22859839/0be40ef2-f09f-11e6-827e-25e91f4e8f63.gif)

**Comment by wells** [comment]
@oyeanuj Fortunately, they fixed that outdent behavior in 0.5.7. See https://github.com/GitbookIO/slate-edit-list/pull/39

**Comment by maxmax1992** [comment]
It still doesnt work for me, when i press backspace when inside list item it still does strange behaviour instead of going to previous list item entry

**Comment by Soreine** [comment]
@maxmax1992 the original issue should be fixed since a long time.
The current behavior is that a first backspace removes the item content from the list (effectively splitting the list), then backspacing again should move the content up to the previous item (effectively joining the list again).

Please open a new issue describing what you would expect to happen if you are still have issues.
